from backend.core.perceptrons.prompts.actors_perceive_agent import actors_perceive_prompt
from backend.core.perceptrons.prompts.features_perceive_agent import features_perceive_prompt
from backend.core.perceptrons.prompts.flows_perceive_agent import flows_perceive_prompt
from backend.core.perceptrons.prompts.scenarios_perceive_agent import scenarios_perceive_prompt