from backend.core.perceptrons.actors_perceptron import ActorsPerceptron, ActorsPerceptronInput
from backend.core.perceptrons.features_perceptron import FeaturesPerceptron, FeaturesPerceptronInput
from backend.core.perceptrons.flows_perceptron import FlowsPerceptron, FlowsPerceptronInput
from backend.core.perceptrons.scenarios_perceptron import ScenariosPerceptron, ScenariosPerceptronInput