from dataclasses import dataclass
import json
from typing import Dict, List

from backend.core.perceptrons.prompts import flows_perceive_prompt
from backend.core.perceptrons.base_perceptron import BasePerceptron, PerceptronInput
from backend.schemas import ActorNode, FeatureNode, FlowNode, BusinessObjectNode


# 为流程感知器定义专属的输入类型
@dataclass
class FlowsPerceptronInput(PerceptronInput):
    user_requirements: str
    actors: List[ActorNode]
    features: List[FeatureNode]
    business_objects: List[BusinessObjectNode]
    flows: List[FlowNode]

class FlowsPerceptron(BasePerceptron[FlowsPerceptronInput]):
    async def perceive(self, input_data: FlowsPerceptronInput) -> Dict:
        user_requirements_ = input_data.user_requirements

        actors_payload = ActorNode.schema(
            many=True,
            only=("actorId", "actorName", "actorDescription")
        ).dump(input_data.actors)

        actors_ = json.dumps(
            {"actors": actors_payload},
            ensure_ascii=False,
            indent=2
        )

        features_payload = FeatureNode.schema(
            many=True,
            only=("featureId", "featureName", "featureDescription", "actorIds")
        ).dump(node for node in input_data.features if len(node.childrenIds) == 0)      # 筛选出没有孩子的结点，即叶子结点

        features_ = json.dumps(
            {"features": features_payload},
            ensure_ascii=False,
            indent=2
        )

        business_objects_payload = BusinessObjectNode.schema(
            many=True,
            only=(
                "businessObjectId",
                "businessObjectName",
                "businessObjectDescription",
                "businessObjectAttributes.businessObjectAttributeId",
                "businessObjectAttributes.businessObjectAttributeName",
                "businessObjectAttributes.businessObjectAttributeDescription",
                "businessObjectAttributes.businessObjectAttributeType",
                "businessObjectAttributes.businessObjectAttributeExample",
            ),
        ).dump(input_data.business_objects)

        flows_payload = FlowNode.schema(
            many=True,
            only=(
                "flowId",
                "flowName",
                "flowDescription",
                "featureIds",
                "flowSteps.stepId",
                "flowSteps.stepName",
                "flowSteps.stepDescription",
                "flowSteps.stepType",
                "flowSteps.actorIds",
                "flowSteps.inputBusinessObjectIds",
                "flowSteps.outputBusinessObjectIds",
                "flowSteps.nextStepIds",
            ),
        ).dump(input_data.flows)

        flows_ = json.dumps(
            {
                "business_objects": business_objects_payload,
                "flows": flows_payload,
            },
            ensure_ascii=False,
            indent=2,
        )

        response = await self._llm_handler.call_llm(
            prompt=flows_perceive_prompt.replace(
                "{{user_requirements}}", user_requirements_).replace(
                "{{actors}}", actors_).replace(
                "{{features}}", features_).replace(
                "{{flows}}", flows_),
            print_log=False,
        )

        return json.loads(response)

if __name__ == "__main__":
    import asyncio
    from backend.schemas import (
        BusinessObjectAttributeNode,
        BusinessObjectNode,
        FlowNode,
        FlowStepNode,
        FlowStepType,
    )

    flows_perceptron = FlowsPerceptron()

    user_requirements = "极简纯净本地音乐播放器，不联网、无会员、无广告，只读取电脑本地音乐文件，支持无损格式 Flac/WAV/MP3 播放，自带歌词本地匹配、音效均衡器、歌单自定义、睡眠定时关闭、全局快捷键切歌，界面清爽轻量化，替代臃肿的主流音乐播放器。"
    test_actors = [
        ActorNode(
            actorId=1,
            actorName="本地音乐听众",
            actorDescription="本地音乐听众是指在需要播放和聆听电脑本地音乐文件的场景下，与音乐播放器发生交互，并可执行导入或扫描本地音乐、播放暂停、切换上一首下一首、调整播放进度、管理播放列表和选择音频格式进行播放等操作的用户角色。"
        ),
        ActorNode(
            actorId=2,
            actorName="歌单管理者",
            actorDescription="歌单管理者是指在需要按个人喜好整理和归类本地音乐的场景下，与歌单管理功能发生交互，并可执行新建歌单、编辑歌单、添加或移除歌曲、排序歌曲、删除歌单和自定义歌单内容等操作的用户角色。"
        ),
        ActorNode(
            actorId=3,
            actorName="音效调节者",
            actorDescription="音效调节者是指在需要根据听感优化音乐播放效果的场景下，与音效设置功能发生交互，并可执行调整均衡器、配置音效参数、切换预设音效和保存个人音效偏好等操作的用户角色。"
        ),
        ActorNode(
            actorId=4,
            actorName="歌词匹配者",
            actorDescription="歌词匹配者是指在需要查看本地歌曲对应歌词的场景下，与歌词匹配功能发生交互，并可执行本地歌词自动匹配、查看歌词显示、调整歌词同步效果和管理歌词关联结果等操作的用户角色。"
        ),
        ActorNode(
            actorId=5,
            actorName="睡眠定时设置者",
            actorDescription="睡眠定时设置者是指在需要限定音乐播放时长并在指定时间自动关闭播放器的场景下，与睡眠定时功能发生交互，并可执行设置定时关闭时间、取消定时、查看倒计时和管理播放结束行为等操作的用户角色。"
        ),
        ActorNode(
            actorId=6,
            actorName="快捷键控制者",
            actorDescription="快捷键控制者是指在需要通过全局快捷键快速控制播放的场景下，与全局快捷键功能发生交互，并可执行设置切歌快捷键、使用快捷键播放暂停、上一首下一首切换和快速调节播放控制等操作的用户角色。"
        ),
        ActorNode(
            actorId=7,
            actorName="界面偏好设置者",
            actorDescription="界面偏好设置者是指在需要让播放器保持清爽、轻量和低干扰使用体验的场景下，与界面设置功能发生交互，并可执行调整界面显示样式、切换轻量化布局、配置视觉风格和管理播放器外观偏好的用户角色。"
        ),
    ]
    test_features: List[FeatureNode] = [
        FeatureNode(
            featureId=1,
            featureName="极简纯净本地音乐播放器",
            featureDescription="系统用于在电脑本地离线播放音乐文件，支持无损与常见音频格式播放，并提供歌词匹配、音效均衡、歌单管理、睡眠定时、全局快捷键和轻量化界面等功能，旨在替代臃肿的主流音乐播放器。",
            actorIds=[1, 2, 3, 4, 5, 6, 7],
            childrenIds=[2, 6, 10, 14, 18, 22, 26]
        ),
        FeatureNode(
            featureId=2,
            featureName="本地音乐播放管理",
            featureDescription="支持读取电脑本地音乐文件并进行播放控制、进度调整和格式播放管理。",
            actorIds=[1],
            childrenIds=[3, 4, 5]
        ),
        FeatureNode(
            featureId=3,
            featureName="扫描与导入本地音乐",
            featureDescription="支持从电脑本地读取、扫描和导入音乐文件，作为播放器的媒体来源。",
            actorIds=[1],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=4,
            featureName="播放控制",
            featureDescription="支持播放、暂停、上一首、下一首和播放进度调整等基础播放操作。",
            actorIds=[1, 6],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=5,
            featureName="音频格式播放",
            featureDescription="支持播放本地无损及常见音频格式文件，包括 Flac、WAV 和 MP3。",
            actorIds=[1],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=6,
            featureName="歌单自定义管理",
            featureDescription="支持用户按个人喜好创建、编辑和维护本地音乐歌单。",
            actorIds=[2, 1],
            childrenIds=[7, 8, 9]
        ),
        FeatureNode(
            featureId=7,
            featureName="新建与删除歌单",
            featureDescription="支持用户创建新的歌单并删除不再需要的歌单。",
            actorIds=[2],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=8,
            featureName="添加或移除歌曲",
            featureDescription="支持用户将本地歌曲添加到歌单中或从歌单中移除。",
            actorIds=[2, 1],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=9,
            featureName="歌单排序与自定义内容",
            featureDescription="支持用户调整歌单内歌曲顺序，并按个人偏好自定义歌单内容。",
            actorIds=[2],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=10,
            featureName="歌词匹配与显示",
            featureDescription="支持本地歌曲歌词自动匹配、显示与同步管理。",
            actorIds=[4],
            childrenIds=[11, 12, 13]
        ),
        FeatureNode(
            featureId=11,
            featureName="本地歌词自动匹配",
            featureDescription="支持根据本地歌曲自动匹配对应歌词文件或歌词内容。",
            actorIds=[4],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=12,
            featureName="歌词显示与同步调整",
            featureDescription="支持在播放界面显示歌词，并调整歌词同步效果以匹配播放进度。",
            actorIds=[4, 1],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=13,
            featureName="歌词关联管理",
            featureDescription="支持用户管理歌词与歌曲的关联结果，便于维护匹配准确性。",
            actorIds=[4],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=14,
            featureName="音效与均衡器设置",
            featureDescription="支持用户根据听感调整音效参数与均衡器配置。",
            actorIds=[3],
            childrenIds=[15, 16, 17]
        ),
        FeatureNode(
            featureId=15,
            featureName="均衡器调节",
            featureDescription="支持用户调整均衡器各频段参数，以优化不同音乐风格的听感。",
            actorIds=[3],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=16,
            featureName="音效参数配置",
            featureDescription="支持用户配置音效相关参数，并保存个人偏好设置。",
            actorIds=[3],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=17,
            featureName="预设音效切换",
            featureDescription="支持用户切换系统提供的预设音效方案。",
            actorIds=[3],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=18,
            featureName="睡眠定时关闭",
            featureDescription="支持设置定时关闭播放器，在指定时间自动停止播放并退出或关闭程序。",
            actorIds=[5],
            childrenIds=[19, 20, 21]
        ),
        FeatureNode(
            featureId=19,
            featureName="设置定时关闭时间",
            featureDescription="支持用户设置播放器在指定时间后自动关闭。",
            actorIds=[5],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=20,
            featureName="取消定时与查看倒计时",
            featureDescription="支持用户取消已设置的定时关闭，并查看剩余倒计时。",
            actorIds=[5],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=21,
            featureName="管理播放结束行为",
            featureDescription="支持用户配置定时结束后播放器的处理方式，如停止播放或关闭程序。",
            actorIds=[5],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=22,
            featureName="全局快捷键控制",
            featureDescription="支持通过系统全局快捷键快速控制音乐播放。",
            actorIds=[6],
            childrenIds=[23, 24, 25]
        ),
        FeatureNode(
            featureId=23,
            featureName="切歌快捷键设置",
            featureDescription="支持用户设置全局切歌快捷键，以便快速控制播放。",
            actorIds=[6],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=24,
            featureName="快捷键播放控制",
            featureDescription="支持通过全局快捷键执行播放、暂停、上一首和下一首操作。",
            actorIds=[6, 1],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=25,
            featureName="快速调节播放状态",
            featureDescription="支持通过快捷键快速调整当前播放状态，提升操作效率。",
            actorIds=[6],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=26,
            featureName="清爽轻量化界面设置",
            featureDescription="支持配置播放器界面风格与显示方式，保持界面简洁、轻量和低干扰。",
            actorIds=[7],
            childrenIds=[27, 28, 29]
        ),
        FeatureNode(
            featureId=27,
            featureName="界面显示样式调整",
            featureDescription="支持用户调整界面显示样式，使播放器保持清爽直观。",
            actorIds=[7],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=28,

            featureName="轻量化布局切换",
            featureDescription="支持用户切换轻量化布局，减少不必要的视觉元素与操作干扰。",
            actorIds=[7],
            childrenIds=[]
        ),
        FeatureNode(
            featureId=29,
            featureName="视觉风格与外观偏好管理",
            featureDescription="支持用户配置播放器视觉风格，满足长期使用中的外观偏好。",
            actorIds=[7],
            childrenIds=[]
        )
    ]

    test_business_objects = [
        BusinessObjectNode(
            businessObjectId=1,
            businessObjectName="本地音乐文件",
            businessObjectDescription="表示从电脑本地读取、扫描或导入的音频文件，是音乐播放、歌单管理、歌词匹配和播放控制的基础数据对象。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=1,
                    businessObjectAttributeName="file_path",
                    businessObjectAttributeDescription="音乐文件在本地电脑中的存储路径。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="D:/Music/周杰伦-晴天.mp3",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=2,
                    businessObjectAttributeName="file_name",
                    businessObjectAttributeDescription="音乐文件名称。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="周杰伦-晴天.mp3",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=3,
                    businessObjectAttributeName="audio_format",
                    businessObjectAttributeDescription="音乐文件的音频格式。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="MP3",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=4,
                    businessObjectAttributeName="duration_seconds",
                    businessObjectAttributeDescription="音乐文件的播放时长，单位为秒。",
                    businessObjectAttributeType="integer",
                    businessObjectAttributeExample="269",
                ),
            ],
        ),
        BusinessObjectNode(
            businessObjectId=2,
            businessObjectName="音乐库",
            businessObjectDescription="表示系统扫描和导入后形成的本地音乐集合，用于支持歌曲检索、播放和歌单添加。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=5,
                    businessObjectAttributeName="library_id",
                    businessObjectAttributeDescription="音乐库唯一标识。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="LIB-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=6,
                    businessObjectAttributeName="music_file_ids",
                    businessObjectAttributeDescription="音乐库中包含的本地音乐文件编号集合。",
                    businessObjectAttributeType="array[string]",
                    businessObjectAttributeExample="[\"M-001\", \"M-002\"]",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=7,
                    businessObjectAttributeName="last_scan_time",
                    businessObjectAttributeDescription="最近一次扫描或导入音乐的时间。",
                    businessObjectAttributeType="datetime",
                    businessObjectAttributeExample="2026-05-20 10:30:00",
                ),
            ],
        ),
        BusinessObjectNode(
            businessObjectId=3,
            businessObjectName="播放会话",
            businessObjectDescription="表示当前音乐播放过程中的状态数据，包括当前歌曲、播放状态、播放进度和播放模式。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=8,
                    businessObjectAttributeName="current_music_id",
                    businessObjectAttributeDescription="当前正在播放或准备播放的音乐文件编号。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="M-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=9,
                    businessObjectAttributeName="play_status",
                    businessObjectAttributeDescription="当前播放状态。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="playing",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=10,
                    businessObjectAttributeName="current_position_seconds",
                    businessObjectAttributeDescription="当前播放进度，单位为秒。",
                    businessObjectAttributeType="integer",
                    businessObjectAttributeExample="85",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=11,
                    businessObjectAttributeName="play_source",
                    businessObjectAttributeDescription="当前播放来源。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="playlist",
                ),
            ],
        ),
        BusinessObjectNode(
            businessObjectId=4,
            businessObjectName="歌单",
            businessObjectDescription="表示用户创建和维护的歌曲集合，用于按照个人偏好分类管理本地音乐。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=12,
                    businessObjectAttributeName="playlist_id",
                    businessObjectAttributeDescription="歌单唯一标识。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="PL-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=13,
                    businessObjectAttributeName="playlist_name",
                    businessObjectAttributeDescription="歌单名称。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="通勤歌曲",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=14,
                    businessObjectAttributeName="song_ids",
                    businessObjectAttributeDescription="歌单中包含的歌曲编号集合。",
                    businessObjectAttributeType="array[string]",
                    businessObjectAttributeExample="[\"M-001\", \"M-003\", \"M-009\"]",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=15,
                    businessObjectAttributeName="sort_rule",
                    businessObjectAttributeDescription="歌单内歌曲排序规则。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="manual",
                ),
            ],
        ),
        BusinessObjectNode(
            businessObjectId=5,
            businessObjectName="歌词文件",
            businessObjectDescription="表示与本地歌曲对应的歌词内容或歌词文件，用于播放界面歌词展示和同步。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=16,
                    businessObjectAttributeName="lyric_id",
                    businessObjectAttributeDescription="歌词文件唯一标识。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="LYR-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=17,
                    businessObjectAttributeName="lyric_path",
                    businessObjectAttributeDescription="歌词文件在本地电脑中的存储路径。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="D:/Lyrics/周杰伦-晴天.lrc",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=18,
                    businessObjectAttributeName="lyric_content",
                    businessObjectAttributeDescription="歌词文本内容。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="[00:12.00]故事的小黄花",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=19,
                    businessObjectAttributeName="time_offset_ms",
                    businessObjectAttributeDescription="歌词同步偏移量，单位为毫秒。",
                    businessObjectAttributeType="integer",
                    businessObjectAttributeExample="500",
                ),
            ],
        ),
        BusinessObjectNode(
            businessObjectId=6,
            businessObjectName="歌词关联结果",
            businessObjectDescription="表示歌曲与歌词之间的匹配或手动关联关系，用于维护歌词显示准确性。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=20,
                    businessObjectAttributeName="association_id",
                    businessObjectAttributeDescription="歌词关联关系唯一标识。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="LRA-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=21,
                    businessObjectAttributeName="music_id",
                    businessObjectAttributeDescription="被关联的音乐文件编号。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="M-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=22,
                    businessObjectAttributeName="lyric_id",
                    businessObjectAttributeDescription="关联的歌词文件编号。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="LYR-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=23,
                    businessObjectAttributeName="match_type",
                    businessObjectAttributeDescription="歌词匹配方式。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="auto",
                ),
            ],
        ),
        BusinessObjectNode(
            businessObjectId=7,
            businessObjectName="音效配置",
            businessObjectDescription="表示用户为优化播放听感而配置的均衡器、预设音效和音效参数。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=24,
                    businessObjectAttributeName="effect_config_id",
                    businessObjectAttributeDescription="音效配置唯一标识。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="EQ-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=25,
                    businessObjectAttributeName="preset_name",
                    businessObjectAttributeDescription="当前使用的预设音效名称。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="Rock",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=26,
                    businessObjectAttributeName="equalizer_values",
                    businessObjectAttributeDescription="均衡器各频段参数集合。",
                    businessObjectAttributeType="object",
                    businessObjectAttributeExample="{\"60Hz\": 3, \"230Hz\": 1, \"910Hz\": -1}",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=27,
                    businessObjectAttributeName="is_saved_as_preference",
                    businessObjectAttributeDescription="是否保存为个人音效偏好。",
                    businessObjectAttributeType="bool",
                    businessObjectAttributeExample="true",
                ),
            ],
        ),
        BusinessObjectNode(
            businessObjectId=8,
            businessObjectName="睡眠定时设置",
            businessObjectDescription="表示用户设置的定时关闭规则，包括倒计时、结束动作和当前状态。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=28,
                    businessObjectAttributeName="timer_id",
                    businessObjectAttributeDescription="睡眠定时设置唯一标识。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="TIMER-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=29,
                    businessObjectAttributeName="duration_minutes",
                    businessObjectAttributeDescription="定时关闭倒计时时长，单位为分钟。",
                    businessObjectAttributeType="integer",
                    businessObjectAttributeExample="30",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=30,
                    businessObjectAttributeName="remaining_seconds",
                    businessObjectAttributeDescription="当前剩余倒计时时长，单位为秒。",
                    businessObjectAttributeType="integer",
                    businessObjectAttributeExample="1200",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=31,
                    businessObjectAttributeName="end_action",
                    businessObjectAttributeDescription="倒计时结束后的处理方式。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="stop_playback",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=32,
                    businessObjectAttributeName="timer_status",
                    businessObjectAttributeDescription="定时器当前状态。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="active",
                ),
            ],
        ),
        BusinessObjectNode(
            businessObjectId=9,
            businessObjectName="快捷键配置",
            businessObjectDescription="表示用户设置的全局快捷键规则，用于快速控制播放、暂停、上一首和下一首。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=33,
                    businessObjectAttributeName="hotkey_config_id",
                    businessObjectAttributeDescription="快捷键配置唯一标识。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="HK-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=34,
                    businessObjectAttributeName="command_name",
                    businessObjectAttributeDescription="快捷键绑定的播放控制命令。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="next_track",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=35,
                    businessObjectAttributeName="key_combination",
                    businessObjectAttributeDescription="快捷键组合。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="Ctrl+Alt+Right",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=36,
                    businessObjectAttributeName="is_global_enabled",
                    businessObjectAttributeDescription="是否启用全局快捷键。",
                    businessObjectAttributeType="bool",
                    businessObjectAttributeExample="true",
                ),
            ],
        ),
        BusinessObjectNode(
            businessObjectId=10,
            businessObjectName="界面偏好设置",
            businessObjectDescription="表示用户对播放器界面样式、轻量化布局和视觉风格的长期偏好配置。",
            businessObjectAttributes=[
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=37,
                    businessObjectAttributeName="interface_preference_id",
                    businessObjectAttributeDescription="界面偏好设置唯一标识。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="UI-001",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=38,
                    businessObjectAttributeName="layout_mode",
                    businessObjectAttributeDescription="当前界面布局模式。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="lightweight",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=39,
                    businessObjectAttributeName="theme_name",
                    businessObjectAttributeDescription="当前视觉主题名称。",
                    businessObjectAttributeType="string",
                    businessObjectAttributeExample="dark",
                ),
                BusinessObjectAttributeNode(
                    businessObjectAttributeId=40,
                    businessObjectAttributeName="show_extra_elements",
                    businessObjectAttributeDescription="是否显示额外视觉元素。",
                    businessObjectAttributeType="bool",
                    businessObjectAttributeExample="false",
                ),
            ],
        ),
    ]

    test_flows = [
        FlowNode(
            flowId=1,
            flowName="本地音乐导入与播放流程",
            flowDescription="用户扫描或导入电脑本地音乐文件，系统识别可播放音频格式并加入音乐库，用户选择歌曲后进行播放控制。",
            featureIds=[1, 2, 3],
            flowSteps=[
                FlowStepNode(
                    stepId=1,
                    stepName="选择音乐导入入口",
                    stepDescription="用户选择扫描本地目录或手动导入音乐文件。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[1],
                    inputBusinessObjectIds=[],
                    outputBusinessObjectIds=[1],
                    nextStepIds=[2],
                ),
                FlowStepNode(
                    stepId=2,
                    stepName="读取本地音乐文件",
                    stepDescription="系统读取用户指定目录或文件，并提取文件路径、文件名、格式和时长等基础信息。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[1],
                    outputBusinessObjectIds=[1],
                    nextStepIds=[3],
                ),
                FlowStepNode(
                    stepId=3,
                    stepName="判断音频格式是否支持",
                    stepDescription="系统判断导入文件是否属于支持的音频格式，如 MP3、WAV 或 Flac。",
                    stepType=FlowStepType.JUDGMENT,
                    actorIds=[],
                    inputBusinessObjectIds=[1],
                    outputBusinessObjectIds=[],
                    nextStepIds=[4, 5],
                ),
                FlowStepNode(
                    stepId=4,
                    stepName="加入音乐库",
                    stepDescription="系统将支持播放的本地音乐文件写入音乐库。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[1],
                    outputBusinessObjectIds=[2],
                    nextStepIds=[6],
                ),
                FlowStepNode(
                    stepId=5,
                    stepName="忽略不支持文件",
                    stepDescription="系统忽略不支持的音频文件，并结束该文件的导入处理。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[1],
                    outputBusinessObjectIds=[],
                    nextStepIds=[],
                ),
                FlowStepNode(
                    stepId=6,
                    stepName="选择歌曲播放",
                    stepDescription="用户从音乐库中选择一首歌曲进行播放。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[1],
                    inputBusinessObjectIds=[2],
                    outputBusinessObjectIds=[3],
                    nextStepIds=[7],
                ),
                FlowStepNode(
                    stepId=7,
                    stepName="执行播放",
                    stepDescription="系统加载用户选择的音乐文件并创建播放会话。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[1, 3],
                    outputBusinessObjectIds=[3],
                    nextStepIds=[8],
                ),
                FlowStepNode(
                    stepId=8,
                    stepName="控制播放状态",
                    stepDescription="用户执行播放、暂停、上一首、下一首或调整播放进度等操作。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[1, 6],
                    inputBusinessObjectIds=[3],
                    outputBusinessObjectIds=[3],
                    nextStepIds=[9],
                ),
                FlowStepNode(
                    stepId=9,
                    stepName="更新播放会话",
                    stepDescription="系统根据用户操作更新当前歌曲、播放状态和播放进度。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[3],
                    outputBusinessObjectIds=[3],
                    nextStepIds=[],
                ),
            ],
        ),
        FlowNode(
            flowId=2,
            flowName="歌单管理流程",
            flowDescription="用户创建或删除歌单，将本地歌曲添加到歌单或从歌单移除，并按照个人偏好调整歌曲顺序。",
            featureIds=[4, 5, 6],
            flowSteps=[
                FlowStepNode(
                    stepId=10,
                    stepName="创建或选择歌单",
                    stepDescription="用户创建新的歌单，或选择已有歌单进行维护。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[2],
                    inputBusinessObjectIds=[4],
                    outputBusinessObjectIds=[4],
                    nextStepIds=[11],
                ),
                FlowStepNode(
                    stepId=11,
                    stepName="保存歌单基础信息",
                    stepDescription="系统保存歌单名称、歌单编号和初始歌曲集合。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[4],
                    outputBusinessObjectIds=[4],
                    nextStepIds=[12],
                ),
                FlowStepNode(
                    stepId=12,
                    stepName="选择歌单操作类型",
                    stepDescription="用户选择添加歌曲、移除歌曲、调整排序或删除歌单。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[2, 1],
                    inputBusinessObjectIds=[2, 4],
                    outputBusinessObjectIds=[],
                    nextStepIds=[13],
                ),
                FlowStepNode(
                    stepId=13,
                    stepName="判断操作类型",
                    stepDescription="系统判断用户当前选择的歌单维护操作。",
                    stepType=FlowStepType.JUDGMENT,
                    actorIds=[],
                    inputBusinessObjectIds=[4],
                    outputBusinessObjectIds=[],
                    nextStepIds=[14, 15, 16, 17],
                ),
                FlowStepNode(
                    stepId=14,
                    stepName="添加歌曲到歌单",
                    stepDescription="系统将用户从音乐库中选择的歌曲加入目标歌单。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[1, 2, 4],
                    outputBusinessObjectIds=[4],
                    nextStepIds=[18],
                ),
                FlowStepNode(
                    stepId=15,
                    stepName="从歌单移除歌曲",
                    stepDescription="系统将用户指定的歌曲从目标歌单中移除。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[4],
                    outputBusinessObjectIds=[4],
                    nextStepIds=[18],
                ),
                FlowStepNode(
                    stepId=16,
                    stepName="调整歌曲顺序",
                    stepDescription="系统根据用户指定的顺序更新歌单内歌曲排序。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[4],
                    outputBusinessObjectIds=[4],
                    nextStepIds=[18],
                ),
                FlowStepNode(
                    stepId=17,
                    stepName="删除歌单",
                    stepDescription="系统删除用户指定的不再需要的歌单。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[4],
                    outputBusinessObjectIds=[],
                    nextStepIds=[],
                ),
                FlowStepNode(
                    stepId=18,
                    stepName="保存歌单变更",
                    stepDescription="系统保存歌单内容和排序变更，供后续播放和管理使用。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[4],
                    outputBusinessObjectIds=[4],
                    nextStepIds=[],
                ),
            ],
        ),
        FlowNode(
            flowId=3,
            flowName="歌词匹配与同步流程",
            flowDescription="系统根据本地歌曲自动匹配歌词，用户查看歌词显示效果，并可调整同步偏移或管理歌词关联关系。",
            featureIds=[7, 8, 9],
            flowSteps=[
                FlowStepNode(
                    stepId=19,
                    stepName="选择需要匹配歌词的歌曲",
                    stepDescription="用户选择一首本地歌曲，触发歌词匹配或歌词显示。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[4, 1],
                    inputBusinessObjectIds=[1],
                    outputBusinessObjectIds=[],
                    nextStepIds=[20],
                ),
                FlowStepNode(
                    stepId=20,
                    stepName="自动查找歌词",
                    stepDescription="系统根据歌曲文件名、歌曲信息或本地歌词目录自动查找对应歌词文件。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[1],
                    outputBusinessObjectIds=[5],
                    nextStepIds=[21],
                ),
                FlowStepNode(
                    stepId=21,
                    stepName="判断歌词是否匹配成功",
                    stepDescription="系统判断是否找到可用歌词，并确认歌词是否可与当前歌曲建立关联。",
                    stepType=FlowStepType.JUDGMENT,
                    actorIds=[],
                    inputBusinessObjectIds=[1, 5],
                    outputBusinessObjectIds=[],
                    nextStepIds=[22, 23],
                ),
                FlowStepNode(
                    stepId=22,
                    stepName="建立歌词关联",
                    stepDescription="系统将匹配到的歌词与当前歌曲建立关联关系。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[1, 5],
                    outputBusinessObjectIds=[6],
                    nextStepIds=[24],
                ),
                FlowStepNode(
                    stepId=23,
                    stepName="手动管理歌词关联",
                    stepDescription="用户手动选择歌词文件或调整歌曲与歌词的关联结果。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[4],
                    inputBusinessObjectIds=[1, 5, 6],
                    outputBusinessObjectIds=[6],
                    nextStepIds=[24],
                ),
                FlowStepNode(
                    stepId=24,
                    stepName="显示歌词",
                    stepDescription="系统在播放界面中按照当前播放进度显示歌词。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[3, 5, 6],
                    outputBusinessObjectIds=[5],
                    nextStepIds=[25],
                ),
                FlowStepNode(
                    stepId=25,
                    stepName="调整歌词同步效果",
                    stepDescription="用户根据播放效果调整歌词时间偏移，使歌词与音乐播放进度一致。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[4, 1],
                    inputBusinessObjectIds=[5],
                    outputBusinessObjectIds=[5],
                    nextStepIds=[26],
                ),
                FlowStepNode(
                    stepId=26,
                    stepName="保存歌词同步设置",
                    stepDescription="系统保存歌词时间偏移和关联结果，供后续播放时复用。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[5, 6],
                    outputBusinessObjectIds=[5, 6],
                    nextStepIds=[],
                ),
            ],
        ),
        FlowNode(
            flowId=4,
            flowName="音效调节流程",
            flowDescription="用户通过预设音效、均衡器和音效参数配置优化音乐播放效果，系统保存并应用个人音效偏好。",
            featureIds=[10, 11, 12],
            flowSteps=[
                FlowStepNode(
                    stepId=27,
                    stepName="打开音效设置",
                    stepDescription="用户进入音效设置界面，准备调整播放效果。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[3],
                    inputBusinessObjectIds=[],
                    outputBusinessObjectIds=[],
                    nextStepIds=[28],
                ),
                FlowStepNode(
                    stepId=28,
                    stepName="选择音效调节方式",
                    stepDescription="用户选择切换预设音效、手动调整均衡器或配置其他音效参数。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[3],
                    inputBusinessObjectIds=[7],
                    outputBusinessObjectIds=[],
                    nextStepIds=[29],
                ),
                FlowStepNode(
                    stepId=29,
                    stepName="判断音效调节方式",
                    stepDescription="系统判断用户选择的是预设音效、均衡器调整还是参数配置。",
                    stepType=FlowStepType.JUDGMENT,
                    actorIds=[],
                    inputBusinessObjectIds=[7],
                    outputBusinessObjectIds=[],
                    nextStepIds=[30, 31, 32],
                ),
                FlowStepNode(
                    stepId=30,
                    stepName="切换预设音效",
                    stepDescription="系统根据用户选择切换到对应的预设音效方案。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[7],
                    outputBusinessObjectIds=[7],
                    nextStepIds=[33],
                ),
                FlowStepNode(
                    stepId=31,
                    stepName="调整均衡器参数",
                    stepDescription="用户调整均衡器各频段参数，形成新的均衡器设置。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[3],
                    inputBusinessObjectIds=[7],
                    outputBusinessObjectIds=[7],
                    nextStepIds=[33],
                ),
                FlowStepNode(
                    stepId=32,
                    stepName="配置音效参数",
                    stepDescription="用户配置其他音效参数，并决定是否保存为个人偏好。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[3],
                    inputBusinessObjectIds=[7],
                    outputBusinessObjectIds=[7],
                    nextStepIds=[33],
                ),
                FlowStepNode(
                    stepId=33,
                    stepName="应用音效配置",
                    stepDescription="系统将新的音效配置应用到当前播放会话。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[3, 7],
                    outputBusinessObjectIds=[3],
                    nextStepIds=[34],
                ),
                FlowStepNode(
                    stepId=34,
                    stepName="保存音效偏好",
                    stepDescription="系统保存用户配置的预设音效、均衡器参数和个人音效偏好。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[7],
                    outputBusinessObjectIds=[7],
                    nextStepIds=[],
                ),
            ],
        ),
        FlowNode(
            flowId=5,
            flowName="睡眠定时关闭流程",
            flowDescription="用户设置定时关闭时间和播放结束行为，系统执行倒计时并在到期后停止播放或关闭程序。",
            featureIds=[13, 14, 15],
            flowSteps=[
                FlowStepNode(
                    stepId=35,
                    stepName="设置定时关闭时间",
                    stepDescription="用户输入定时关闭时长或指定关闭时间。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[5],
                    inputBusinessObjectIds=[],
                    outputBusinessObjectIds=[8],
                    nextStepIds=[36],
                ),
                FlowStepNode(
                    stepId=36,
                    stepName="设置播放结束行为",
                    stepDescription="用户选择倒计时结束后的处理方式，如停止播放或关闭程序。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[5],
                    inputBusinessObjectIds=[8],
                    outputBusinessObjectIds=[8],
                    nextStepIds=[37],
                ),
                FlowStepNode(
                    stepId=37,
                    stepName="启动倒计时",
                    stepDescription="系统保存定时关闭设置并启动倒计时。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[8],
                    outputBusinessObjectIds=[8],
                    nextStepIds=[38],
                ),
                FlowStepNode(
                    stepId=38,
                    stepName="查看或取消倒计时",
                    stepDescription="用户查看剩余倒计时，或取消已经设置的定时关闭。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[5],
                    inputBusinessObjectIds=[8],
                    outputBusinessObjectIds=[8],
                    nextStepIds=[39],
                ),
                FlowStepNode(
                    stepId=39,
                    stepName="判断定时状态",
                    stepDescription="系统判断定时任务是已取消、继续倒计时还是已经到期。",
                    stepType=FlowStepType.JUDGMENT,
                    actorIds=[],
                    inputBusinessObjectIds=[8],
                    outputBusinessObjectIds=[],
                    nextStepIds=[40, 41, 42],
                ),
                FlowStepNode(
                    stepId=40,
                    stepName="取消定时任务",
                    stepDescription="系统取消当前睡眠定时任务，并清除倒计时状态。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[8],
                    outputBusinessObjectIds=[8],
                    nextStepIds=[],
                ),
                FlowStepNode(
                    stepId=41,
                    stepName="继续倒计时",
                    stepDescription="系统继续维护倒计时并更新剩余时间。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[8],
                    outputBusinessObjectIds=[8],
                    nextStepIds=[38],
                ),
                FlowStepNode(
                    stepId=42,
                    stepName="执行结束行为",
                    stepDescription="系统在倒计时结束后按照用户配置停止播放或关闭程序。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[3, 8],
                    outputBusinessObjectIds=[3, 8],
                    nextStepIds=[],
                ),
            ],
        ),
        FlowNode(
            flowId=6,
            flowName="全局快捷键控制流程",
            flowDescription="用户配置全局快捷键，系统校验并保存快捷键绑定，用户通过快捷键快速执行播放控制操作。",
            featureIds=[16, 17, 18],
            flowSteps=[
                FlowStepNode(
                    stepId=43,
                    stepName="进入快捷键设置",
                    stepDescription="用户打开快捷键设置入口，准备配置播放控制快捷键。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[6],
                    inputBusinessObjectIds=[],
                    outputBusinessObjectIds=[],
                    nextStepIds=[44],
                ),
                FlowStepNode(
                    stepId=44,
                    stepName="配置快捷键组合",
                    stepDescription="用户为播放、暂停、上一首和下一首等命令设置快捷键组合。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[6],
                    inputBusinessObjectIds=[],
                    outputBusinessObjectIds=[9],
                    nextStepIds=[45],
                ),
                FlowStepNode(
                    stepId=45,
                    stepName="校验快捷键冲突",
                    stepDescription="系统校验快捷键组合是否为空、重复或与已有快捷键冲突。",
                    stepType=FlowStepType.JUDGMENT,
                    actorIds=[],
                    inputBusinessObjectIds=[9],
                    outputBusinessObjectIds=[],
                    nextStepIds=[46, 47],
                ),
                FlowStepNode(
                    stepId=46,
                    stepName="提示重新设置",
                    stepDescription="系统提示快捷键不可用，要求用户重新设置快捷键组合。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[9],
                    outputBusinessObjectIds=[],
                    nextStepIds=[44],
                ),
                FlowStepNode(
                    stepId=47,
                    stepName="保存快捷键配置",
                    stepDescription="系统保存有效的快捷键配置并启用全局快捷键监听。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[9],
                    outputBusinessObjectIds=[9],
                    nextStepIds=[48],
                ),
                FlowStepNode(
                    stepId=48,
                    stepName="触发快捷键",
                    stepDescription="用户在任意场景下按下已配置的全局快捷键。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[6, 1],
                    inputBusinessObjectIds=[9],
                    outputBusinessObjectIds=[],
                    nextStepIds=[49],
                ),
                FlowStepNode(
                    stepId=49,
                    stepName="识别快捷键命令",
                    stepDescription="系统根据快捷键配置识别用户触发的播放控制命令。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[9],
                    outputBusinessObjectIds=[],
                    nextStepIds=[50],
                ),
                FlowStepNode(
                    stepId=50,
                    stepName="执行播放控制",
                    stepDescription="系统执行对应的播放、暂停、上一首、下一首或快速调节播放状态操作。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[3, 9],
                    outputBusinessObjectIds=[3],
                    nextStepIds=[],
                ),
            ],
        ),
        FlowNode(
            flowId=7,
            flowName="界面偏好设置流程",
            flowDescription="用户调整播放器界面显示样式、轻量化布局和视觉风格，系统保存并应用界面偏好。",
            featureIds=[19, 20, 21],
            flowSteps=[
                FlowStepNode(
                    stepId=51,
                    stepName="进入界面设置",
                    stepDescription="用户进入播放器界面设置入口。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[7],
                    inputBusinessObjectIds=[],
                    outputBusinessObjectIds=[],
                    nextStepIds=[52],
                ),
                FlowStepNode(
                    stepId=52,
                    stepName="调整界面显示样式",
                    stepDescription="用户调整界面显示样式、视觉风格或是否显示额外视觉元素。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[7],
                    inputBusinessObjectIds=[10],
                    outputBusinessObjectIds=[10],
                    nextStepIds=[53],
                ),
                FlowStepNode(
                    stepId=53,
                    stepName="选择布局模式",
                    stepDescription="用户选择标准布局或轻量化布局，以减少操作干扰。",
                    stepType=FlowStepType.ACTOR_ACTION,
                    actorIds=[7],
                    inputBusinessObjectIds=[10],
                    outputBusinessObjectIds=[10],
                    nextStepIds=[54],
                ),
                FlowStepNode(
                    stepId=54,
                    stepName="应用界面偏好",
                    stepDescription="系统根据用户选择立即调整界面布局、视觉风格和显示元素。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[10],
                    outputBusinessObjectIds=[10],
                    nextStepIds=[55],
                ),
                FlowStepNode(
                    stepId=55,
                    stepName="保存界面设置",
                    stepDescription="系统保存用户界面偏好，供后续启动播放器时自动加载。",
                    stepType=FlowStepType.SYSTEM_ACTION,
                    actorIds=[],
                    inputBusinessObjectIds=[10],
                    outputBusinessObjectIds=[10],
                    nextStepIds=[],
                ),
            ],
        ),
    ]

    async def main():
        flows_perceptron_result = await flows_perceptron.perceive(
            FlowsPerceptronInput(user_requirements, test_actors, test_features,test_business_objects, test_flows)
        )
    asyncio.run(main())

    result = """
{
  "perceptionDescription": "需要补充系统流程。\n\n需要补充什么：\n1) 应用启动/退出与本地数据持久化流程（配置加载、库/歌单/关联数据加载、退出时保存）。\n2) 音乐库增量维护流程（再次扫描、文件变更/丢失处理、库去重与更新索引）。\n3) 从歌单发起播放与播放队列生成流程（选择歌单->生成播放队列->更新播放会话来源与当前曲目）。\n4) 播放异常与降级处理流程（文件无法读取/解码失败、歌词缺失或不可用、音频设备不可用等情况下的提示与跳过策略）。\n\n为何需要补充：\n- 当前流程覆盖“导入/播放、歌单、歌词、音效、定时、快捷键、界面”，但缺少跨模块的生命周期与持久化主流程，导致无法解释“清爽轻量但可长期使用”的核心体验（重启后库/歌单/歌词关联/音效/快捷键/界面偏好如何恢复）。\n- 音乐只读取本地文件，真实使用中经常发生文件移动/删除/新增；现有仅一次性导入，缺少库一致性维护流程会造成大量失效条目与播放失败。\n- 当前播放流程仅描述从音乐库选歌播放，播放会话里却出现 play_source=playlist，但没有“从歌单播放/队列”的独立流程，流程间衔接不完整。\n- “极简纯净”要求出现错误时不打断体验；缺少统一异常流程会让播放控制、歌词、快捷键等在失败时行为不可控。\n\n如何补充：\n- 新增 business object（或在现有对象上补属性）以支撑上述流程：\n  a) 本地存储状态/配置仓库（包含 library_id、playlist_ids、last_opened_playlist、last_play_session_snapshot、各类偏好版本与保存时间）。\n  b) 播放队列（queue_id、track_ids、current_index、queue_source=library/playlist、repeat_mode、shuffle_enabled）。\n  c) 扫描任务/索引状态（scan_job_id、target_paths、scan_type=full/incremental、added/updated/removed 统计、error_list）。\n  d) 播放错误事件（error_id、music_id、error_type、action_taken=skip/retry/stop）。\n- 在 flows 中补 4 条流程，并让其与现有流程通过输入输出对象衔接：\n  1) “应用启动与数据加载流程”：启动->读取本地存储->加载音乐库/歌单/歌词关联/各类偏好->（可选）恢复播放会话/播放队列。\n  2) “音乐库增量扫描与一致性维护流程”：选择扫描策略->扫描路径->对比索引->新增/更新/移除条目->更新音乐库与歌单内失效引用处理策略（标记失效/自动移除）。\n  3) “歌单发起播放与队列生成流程”：选择歌单->生成播放队列->创建/更新播放会话(play_source=playlist)->进入播放控制（复用现有播放控制步骤）。\n  4) “播放异常处理流程”：播放中捕获错误->判断错误类型->执行跳过/重试/停止->更新播放会话与错误记录，并在 UI 以轻提示呈现。"
}
"""