from backend.core.generators.prompts.actors_generate_agent import actors_generate_prompt
from backend.core.generators.prompts.features_generate_agent import features_generate_prompt
from backend.core.generators.prompts.flows_generate_agent import flows_generate_prompt
from backend.core.generators.prompts.scenarios_generate_agent import scenarios_generate_prompt